apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m3sakj9s6-python
  janus-idp.io/tekton: m3sakj9s6-python
  backstage.io/kubernetes-id: m3sakj9s6-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m3sakj9s6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
